### ISSUE TITLE
VK_EXT_image_drm_format_modifier

### ISSUE THREAD

**Issue by letalvoj** [Yours3lf/rpi-vk-driver#11]
Sorry, this is more like a question & _possible_ feature request.

It seems that for a Vulkan backed Wayland compositor to work the `VK_EXT_image_drm_format_modifier` should be supported. https://github.com/swaywm/wlroots/pull/1214#issuecomment-647771405
Having a snappy responsive WM on an old power efficient RPi would be as cool as running games on it.

What is the current state of `VK_EXT_image_drm_format_modifier`? Any chance it could be supported in the future?

Amazin job btw.

**Comment by Yours3lf** [comment]
Hey,

some support for this is already present, buffers are assigned a tiling mode depending on their sizes, see here:
https://github.com/Yours3lf/rpi-vk-driver/blob/922c6ff139845b4deeac9e2d06dd9df1ba487820/driver/kernelInterface.c#L186

I don't think it would be much work to support this extension. Not sure about how this works together with Wayland though.

Please feel free to submit a pull request once you've got it working :)

thanks!

**Comment by letalvoj** [comment]
Cool.

> Please feel free to submit a pull request once you've got it working :)

Yeah, I'd love to! The same way how I would like to update some formulas in homebrew. Unfortunately both C and Ruby look like a giberish to me. 😞

**Comment by Yours3lf** [comment]
Well that's exactly what the Raspberry Pi is about, learning programming! 
I can only recommend C being pretty simple.

**Comment by paulwratt** [comment]
I just submitted a patch for a python app. I have never programmed in Python. if you test your changes, and use both the local code as reference and the internet for help, @letalvoj you could achieve your goal.

**Comment by letalvoj** [comment]
I assume that what @Yours3lf meant by
> I don't think it would be much work to support this extension. Not sure about how this works together with Wayland though.

involves studying specification of the extension and a more than few lines of C code. If I ever get to this it will be after swaywm/wlroots#1214 gets merged and the Vulkan support in Sway gets stable. Unfortunatelly it does not seem to be anytime soon.

Thanks for your insight and positive attitude :)
