### ISSUE TITLE
[Pi4] Couldn't get V3D IDENT0: Invalid argument

### ISSUE THREAD

**Issue by n00b7** [Yours3lf/rpi-vk-driver#13]
Vulkaninfo:
Couldn't get V3D IDENT0: Invalid argument     <-----------------------------------------------
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
Cannot create Vulkan instance.
/build/vulkan-tools-hvsg2w/vulkan-tools-1.1.97+dfsg1/vulkaninfo/vulkaninfo.c:918: failed with VK_ERROR_INCOMPATIBLE_DRIVER

PI 4 With FULL KMS[new kernel 5.4]

Does this mean that the externals need updated for VC6[drm headers, brcm headers]

**Comment by Yours3lf** [comment]
This driver does not support the Raspberry Pi 4
