### ISSUE TITLE
Question regarding Performance Recs / Resolution Wiki Section

### ISSUE THREAD

**Issue by drudru** [Yours3lf/rpi-vk-driver#18]
Hi - first off... this is a really impressive project!

I have a question regarding the Wiki. In the Performance Recomendations, under 'Resolution', you recommend 720p.
Can you elaborate on this? Is there a rough threshold?

What if I'm rendering: video, a compositing desktop, or a full-screen game emulator?
In some of the examples, I suspect that the HVS (hardware video scaler) can do some of the heavy lifting as well.
I haven't dug into the code, but I would bet that you are not interacting with the HVS.

**Comment by Yours3lf** [comment]
Hi 

The max resolution the gpu can render to is 2048x2048 - this is a hard limit. However, in the Videocore IV architecture reference they mention performance specs at 720p. Given that this GPU is rougly on par with an iPhone 4 that’s spot on.

“ A fully configured system will support 720p resolution with 4x multisampling at good frame rates with next generation game content “

So you can use 1080p without issues just scale back the pixel workload.
I think composition should be fine but maybe for games you should use 720p.

Not sure how HVS works.

**Comment by drudru** [comment]
Excellent, thanks. I think I can pull off some simple stuff at 1080p given this.

wrt to HVS, here is a great introduction:

https://blog.benjdoherty.com/2019/05/21/Exploring-Hardware-Compositing-With-the-Raspberry-Pi/

cheers

**Comment by Yours3lf** [comment]
Sweet, what are you planning on doing btw?

**Comment by drudru** [comment]
Hi, I have an older Raspberry Pi 3 and I was considering playing with graphics on it. 
Sort of a repl for shaders. I wanted to test out basic 2d graphics primitives using different algos.
So, I would have been taking the system to the max.

:+1:
