### ISSUE TITLE
flipQueueThreadFunction pthread_create passing fd as pointer is dodgy?

### ISSUE THREAD

**Issue by pjx3** [Yours3lf/rpi-vk-driver#19]
Hello, 

I've been getting random hangs when calling vkAcquireNextImageKHR due to the device handle passed to vc4_seqno_wait being corrupted in the flipQueueThreadFunction. I think the problem is that the fd argument is passed as a pointer on creation of that thread in modeset_create_surface_for_mode(). fd here is a local variable so when pthread_create eventually fires up the flipQueueThreadFunction it (the local fd) seems to have gone out of scope (i.e. the pointer is invalid). 

So, I simply changed the create to pass the value...

		pthread_create(&flipQueueThread, 0, flipQueueThreadFunction, fd);

and the thread function's start up to...

	int threadFD = (int)vargp;

and now get consistent fd's and no hangs in vc4_seqno_wait.

Not sure if you want to roll that into trunk or if I've misunderstood the intent?

Cheers,
Pete

**Comment by Yours3lf** [comment]
Hey Pete, 

good catch! 
Please submit a pull request and I’ll merge it right away!

Thanks 😊

**Comment by pjx3** [comment]
done @ #20
