### ISSUE TITLE
Question about Yocto testing/integration.

### ISSUE THREAD

**Issue by dev-0x7C6** [Yours3lf/rpi-vk-driver#24]
Hi,

I found in commit history that this driver was tested with Yocto. Can I borrow original recipe from somewhere?

I created one by myself but I ran in problem that `cmake` cannot find `python` executable (`find_program`). Not sure what is wrong, mine recipe looks like this:

```
DESCRIPTION = "VK driver for the Raspberry Pi (Broadcom Videocore IV)"

inherit cmake python3-dir python3native

LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=0e9db807e4f1ed14373059c8499d5f82"

SRC_URI = "git://github.com/Yours3lf/rpi-vk-driver.git"
SRCREV = "39bb5f20e39185bf41a636a238437d55dc6ded5a"

PV = "1.0+git${SRCPV}"
S = "${WORKDIR}/git"

OECMAKE_FIND_ROOT_PATH_MODE_PROGRAM = "BOTH"
```

Thanks for making this driver, I'm exited to try it out :-)
Bartłomiej

**Comment by Yours3lf** [comment]
@jwinarske can you please help me out here?

**Comment by dev-0x7C6** [comment]
@Yours3lf Thanks for mentioning @jwinarske. I found original recipe in his [meta-flutter](https://github.com/jwinarske/meta-flutter) layer (recipe: [rpi-vk-driver.bb](https://github.com/jwinarske/meta-flutter/blob/zeus/recipes-graphics/rpi-vk-driver/rpi-vk-driver_git.bb)). I think I know now how to progress with my problem :) thanks.

@jwinarske Maybe it's worth to submit your layer here - https://layers.openembedded.org/. I'll borrow `rpi-vk-driver.bb` recipe to my `meta-retro` with comment about original place and author :-)
