### ISSUE TITLE
All tests using Vuklan API fail with SEGFAULT

### ISSUE THREAD

**Issue by fabiopolimeni** [Yours3lf/rpi-vk-driver#25]
**Describe the bug**
Once the driver is built and installed following the instructions on the BUILD.md, I can't run any test that makes use of the Vulkan API, all of them fail with a SEGFAULT.

**To Reproduce**
Execute `test/mintest/mintest` 

```
Can't open device file: /dev/dri/card0
Error: No such file or directory
Sgmentation fault
```

**Expected behavior**
The test should succeed with no error.

**Device information (please complete the following information):**
 - Device info: Raspberry Pi 3 Model A+)
 - OS information: Linux version 5.4.79-v7+ (Raspbian GNU/Linux10 buster)

**Additional context**
I guess the assumption at this line is no longer valid
https://github.com/Yours3lf/rpi-vk-driver/blob/39bb5f20e39185bf41a636a238437d55dc6ded5a/driver/instance.c#L186

**Comment by fabio-polystream** [comment]
Solved. Because running in CLI somehow removed the `dtoverlay=vc4-fkms-v3d` setting this back has solved the problem, now _only_ three tests fail.

**Comment by fabiopolimeni** [comment]
Solved by adding `dtoveraly=vc4-fkms-v3d` to the `config.txt` file. Starting in CLI doesn't need it and for some reason, it was disabled. Adding it back fixed the issue.
