### ISSUE TITLE
at install : warning everywhere

### ISSUE THREAD

**Issue by QSDDS** [Yours3lf/rpi-vk-driver#27]
**Describe the bug**
Frequency of occurance. Command line output. Stack trace.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device information (please complete the following information):**
 - Device info (eg. Raspberry Pi 3 Model A+)
 - OS information (cat /proc/version, lsb_release -a)
 - Kernel module information: lsmod
 - Driver version (git commit ID or release info)

**Additional context**

**Comment by Yours3lf** [comment]
please fill out the bug report otherwise I'll have to close this

**Comment by QSDDS** [comment]
I tried to install it following the instructions, I got the message "warning" everywhere. In addition I was forced to reinstall raspbian. And I don't want to start over.
On rpi3b+ raspbian (pios) full

**Comment by QSDDS** [comment]
Just a final question, are you using a virtual machine for development or are you developing directly on the raspberry computer?

**Comment by Yours3lf** [comment]
hey not sure what went wrong there tbh, if you followed the guide it should work.
I was developing on a virtual machine and deployed over wifi

**Comment by QSDDS** [comment]
Okay, sorry to bother you, the problem must be with me.
