### ISSUE TITLE
Why not based on Mesa

### ISSUE THREAD

**Issue by abergmeier** [Yours3lf/rpi-vk-driver#3]
I am wondering why this does not seem to be based on mesa. At least this would provider a lot of boilerplate.

**Comment by Yours3lf** [comment]
I wanted to start from scratch in a simple C project exploring how to write a GPU driver. It's been a learning experience for me too. I suppose you could put all this under Mesa if you wanted to.

**Comment by abergmeier** [comment]
Thanks. I started now with a fresh implementation based on mesa - but targeting VC6: https://github.com/abergmeier/mesa-vulkan-broadcom

**Comment by Yours3lf** [comment]
I wish you good luck!
Fyi Eric Anholt implemented the VC5 driver under mesa, might be interesting to you:
https://github.com/anholt/

**Comment by abergmeier** [comment]
> I wish you good luck!

Thanks. Need all the luck that I can get ;)

> Fyi Eric Anholt implemented the VC5 driver under mesa, might be interesting to you:

Already talked with Eric. He did attempt a VC5 vulkan but never got it quite to compile. So I am starting with a `libvulkan_broadcom.so`, that always compiles and slowly move features into that.

**Comment by darkdragon-001** [comment]
You should coordinate your effort with [Igalia](https://gitlab.freedesktop.org/apinheiro/mesa/-/tree/wip/igalia/v3dv) ([status blog post](https://www.raspberrypi.org/blog/vulkan-update-now-with-added-source-code/)) which is under contract with the Raspberry Pi Foundation to work on this issue.
