### ISSUE TITLE
Rpi4 support

### ISSUE THREAD

**Issue by burt111** [Yours3lf/rpi-vk-driver#4]
Just wondering if this would still work on the pi with videocore vi or is it incompatible

**Comment by Yours3lf** [comment]
I have no idea how the VC 6 works, it's probably completely different. My guess is no.

**Comment by Askmewho** [comment]
For what I hear its not much diferent than vc4... and its vulkan capable on the hardware. There is no more mesa development for now (not really active at least, just minor fixes).

**Comment by abergmeier** [comment]
Should we ever have a working Vulkan driver for VC6 in mesa, I think it would be easier to "migrate"  necessary VC4 code to mesa.
That said - I think we are still years away ;)

**Comment by tlosm** [comment]
This is on pi4 ... 

pi@raspberrypi:~/src/mesa-/rpi-vk-driver $ ./depthTex
supported extensions:
	VK_KHR_get_display_properties2
	VK_KHR_get_physical_device_properties2
	VK_KHR_get_surface_capabilities2
	VK_KHR_surface
	VK_KHR_xcb_surface
	VK_KHR_xlib_surface
	VK_KHR_display
	VK_EXT_direct_mode_display
	VK_EXT_acquire_xlib_display
	VK_EXT_display_surface_counter
	VK_EXT_debug_report
	VK_KHR_external_memory_capabilities
	VK_EXT_debug_utils
created vulkan instance
physical device with vulkan support found
physical device supports version 1.1.102
segmentation error

**Comment by Yours3lf** [comment]
this driver only supports the Videocore IV GPU, so only RPi 0, 1, 2, 3 are supported.

**Comment by darkdragon-001** [comment]
Official Raspberry Pi 4 Vulkan driver is [in development](https://gitlab.freedesktop.org/apinheiro/mesa/-/tree/wip/igalia/v3dv) by the consulting firm [Igalia](https://www.raspberrypi.org/blog/vulkan-raspberry-pi-first-triangle/) with a recent [status update](https://www.raspberrypi.org/blog/vulkan-update-now-with-added-source-code/).

Previous MESA efforts for VC4 Vulkan support can be found in some vc4/v3d WIP branches by [Eric Anholt](https://gitlab.freedesktop.org/anholt/mesa).

See [Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=Raspberry-Pi-Vulkan-Summer-2020) for good media coverage (this is how I became aware of the project in the first place)!
