### ISSUE TITLE
just curoiusity

### ISSUE THREAD

**Issue by Askmewho** [Yours3lf/rpi-vk-driver#5]
Hi, why not move this development to a vk capable VC6 (which its in some way similar to vc4). you should join mesa development, imo. cheers

**Comment by Yours3lf** [comment]
Hi,

thank you for your interest in the project!

I addressed these questions here and here:
https://github.com/Yours3lf/rpi-vk-driver/issues/4
https://github.com/Yours3lf/rpi-vk-driver/issues/3
