### ISSUE TITLE
Clarification on SPIR-V support status ?

### ISSUE THREAD

**Issue by Hugobros3** [Yours3lf/rpi-vk-driver#7]
The current README reads: 

> It also offers a wider feature set such as MSAA support, low level assembly shaders and performance counters. On the other hand it currently does not support GLSL shaders.

That's a weird thing to say since Vulkan itself doesn't know anything about GLSL by default, instead it consumes SPIR-V IR code, which makes it quite unclear if this is what's referred to by "low level assembly shaders".

Wether or not this supports SPIR-V is a pretty big deal and should be said more clearly. If those "low level assembly shaders" actually mean VideoCore specific code (which is my current understanding of this), that too should be said in unambiguous terms.

Cool stuff otherwise !

**Comment by Yours3lf** [comment]
Yea I’m just used to GLSL I guess :)
I does not support spirv at this moment but it should be easy to integrate it (if you want to do it).
Or you can also write a compiler from any language to the RPi assemly and just supply the descriptor/push constant mapping table. The limit is your imagination!
