### ISSUE TITLE
Suspicious snippet of code inside clInsertConfigurationBits

### ISSUE THREAD

**Issue by ShFil119** [Yours3lf/rpi-vk-driver#8]
In file `ControlListUtil.c ` in function `clInsertConfigurationBits` I've seen:
```
	memcpy(getCPAptrFromOffset(cl->CPA, cl->nextFreeByteOffset), &tmp, sizeof(uint32_t));
	cl->nextFreeByteOffset += 3;
```
It looks kinda suspicious. 

(if it's bug maybe it's better to use `cl->nextFreeByteOffset += sizeof(uint32_t);`? )
Edit: or maybe even macro wrapper?

**Comment by Yours3lf** [comment]
Yea fair enough, but I’m only using 3 bytes and the fourth one will be unused anyways
